//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int32_t function_1030(char * format, ...);
void function_1040(int64_t * d);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1130;
int64_t g2 = 0x10f0;
int64_t g3 = 0;
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1017
int64_t _init(void) {
    // 0x1000
    int64_t result; // 0x1016
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1010
        __gmon_start__();
        result = &g4;
    } else {
        result = 0;
    }
    // 0x1012
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
void function_1040(int64_t * d) {
    // 0x1040
    __cxa_finalize(d);
}

// Address range: 0x1050 - 0x107b
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x1050
    int64_t v1;
    __libc_start_main(0x1135, (int32_t)a4, (char **)&v1, (void (*)())0x1160, (void (*)())0x11c0, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t deregister_tm_clones(void) {
    // 0x1080
    return &g3;
}

// Address range: 0x10b0 - 0x10e9
int64_t register_tm_clones(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1129
int64_t __do_global_dtors_aux(void) {
    // 0x10f0
    if (*(char *)&g3 != 0) {
        // 0x1128
        int64_t result; // rax
        return result;
    }
    if (*(int64_t *)0x3ff8 != 0) {
        // 0x1107
        __cxa_finalize((int64_t *)*(int64_t *)0x4008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1113
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x1130 - 0x1135
int64_t frame_dummy(void) {
    // 0x1130
    return register_tm_clones();
}

// Address range: 0x1135 - 0x1151
int main(int argc, char ** argv) {
    // 0x1135
    printf("Hello There!");
    return 0;
}

// Address range: 0x1160 - 0x11bd
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x1188
    if (((int64_t)&g2 - (int64_t)&g1) / 8 != 0) {
        int64_t v1 = 0; // 0x11a52
        while (v1 + 1 != ((int64_t)&g2 - (int64_t)&g1) / 8) {
            // 0x1198
            v1++;
        }
    }
    // 0x11ae
    return result;
}

// Address range: 0x11c0 - 0x11c1
int64_t __libc_csu_fini(void) {
    // 0x11c0
    int64_t result; // rax
    return result;
}

// Address range: 0x11c4 - 0x11cd
int64_t _fini(void) {
    // 0x11c4
    int64_t result; // rax
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.3.0)
// Detected functions: 12
// Decompilation date: 2019-05-19 09:11:39
